### ISSUE TITLE
Add autocommit option to pgdb

### ISSUE THREAD

**Issue by qakapil** [Cito/PyGreSQL#8]
CREATE DATABASE command is failing with transactional block error. And there is no option to set auto-commit. Is there no way we can create database with Pygresql DB API2 ?

**Comment by Cito** [comment]
Right, DB API 2 operations always run in a transaction. We would need to add a non-standard attribute or methods to change that behavior. I have created a [Trac Ticket](http://trac.pygresql.org:8000/pgtracker/ticket/75) for this since it would be a useful addition.

Luckily, PyGreSQL provides the classic interface that runs in auto-commit mode, so you cna use that to run commands such as "create database" or "vacuum";

    from pg import DB
    db = DB(dbname='postgres', user='postgres')
    db.query('create database mydb')

**Comment by qakapil** [comment]
Thanks. So the classic Pygresql interface only supports auto-commit mode ?
Can we switch off auto-commit in classic Pygresql ?

Thanks.
Kapil.

**Comment by Cito** [comment]
In classic PyGreSQL you simply put your `db.query()`s between `db.begin()` and `db.end()` calls if you want to run them in a transaction (see section on [transaction handling](http://www.pygresql.org/contents/pg/db_wrapper.html#begin-commit-rollback-savepoint-release-transaction-handling)).
